# Generated by Django 3.2.22 on 2024-01-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0055_auto_20231031_1034"),
        ("NEMO", "0055_reservationconfigurationoption"),
    ]

    operations = []
