# Generated by Django 3.2.22 on 2024-01-17 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NEMO', '0056_merge_20240102_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NEMO.accounttype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='application_identifier',
            field=models.CharField(max_length=100),
        ),
    ]
